### ISSUE TITLE
Stream Error

### ISSUE THREAD

**Issue by semwaqas** [crypto-browserify/cipher-base#22] opened 2024-06-09 00:21 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `cipher-base@1.0.4` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/cipher-base/index.js b/node_modules/cipher-base/index.js
index 6728005..fd5ada7 100644
--- a/node_modules/cipher-base/index.js
+++ b/node_modules/cipher-base/index.js
@@ -1,5 +1,5 @@
 var Buffer = require('safe-buffer').Buffer
-var Transform = require('stream').Transform
+var Transform = require('stream-browserify').Transform
 var StringDecoder = require('string_decoder').StringDecoder
 var inherits = require('inherits')
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by shirakaba** [comment] 2024-08-06 08:10
Here's a pnpm patch to place into your `patches` folder, too!

`cipher-base@1.0.4.patch`:
```diff
diff --git a/.npmignore b/.npmignore
deleted file mode 100644
index 3c3629e647f5ddf82548912e337bea9826b434af..0000000000000000000000000000000000000000
diff --git a/index.js b/index.js
index 6728005e957d3399d9b43e73da72c164140e2b48..fd5ada76393dc3dc248429c347245a936819ca17 100644
--- a/index.js
+++ b/index.js
@@ -1,5 +1,5 @@
 var Buffer = require('safe-buffer').Buffer
-var Transform = require('stream').Transform
+var Transform = require('stream-browserify').Transform
 var StringDecoder = require('string_decoder').StringDecoder
 var inherits = require('inherits')
```

**Comment by ljharb** [comment] 2024-11-16 06:43
Duplicate of #17.

**Closed as not planned by ljharb** 2024-11-16 06:43 UTC
